export const ActionTypes = {
    SIGNUP_USER: "SIGNUP_USER",
    ADD_USER: "ADD_USER",
    SET_USER:"SET_USER",
    SET_INVALID_USERS:"SET_INVALID_USERS",
    REGISTER_USER:"REGISTER_USER",
    DECLINE_USER:"DECLINE_USER",
    SET_PRODUCTS:"SET_PRODUCTS",
    SET_STATIONERY:"SET_STATIONERY",
    SET_NOTES:"SET_NOTES",
    SET_ENOTES:"SET_ENOTES",
    SET_PREVIOUS_PAPERS:"SET_PREVIOUS_PAPERS",
    SET_MY_PRODUCTS:"SET_MY_PRODUCTS",   //Unrequired
    

    SET_ALL_PRODUCTS_BUTTON:"SET_ALL_PRODUCTS_BUTTON",
    SET_STATIONERY_BUTTON:"SET_STATIONERY_BUTTON",
    SET_NOTES_BUTTON:"SET_NOTES_BUTTON",
    SET_ENOTES_BUTTON:"SET_ENOTES_BUTTON",
    SET_PREVIOUS_PAPERS_BUTTON:"SET_PREVIOUS_PAPERS_BUTTON",

    SEARCH_ALL_PRODUCTS: "SEARCH_ALL_PRODUCTS",
    SEARCH_STATIONERY: "SEARCH_STATIONERY",
    SEARCH_NOTES:"SEARCH_NOTES",
    SEARCH_PREVIOUS_PAPERS:"SEARCH_PREVIOUS_PAPERS",
    SEARCH_ENOTES:"SEARCH_ENOTES",
    BOOK_PRODUCT:"BOOK_PRODUCT",

    SET_AVAILABLE_PRODUCTS:"SET_AVAILABLE_PRODUCTS",
    SET_BOOKED_PRODUCTS:"SET_BOOKED_PRODUCTS",
    SET_TRANSACTION_HISTORY:"SET_TRANSACTION_HISTORY",

    DELETE_PRODUCT:"DELETE_PRODUCT",
}